In [15]:
from pathlib import Path
import pandas as pd


PROJECT_ROOT = Path.cwd().parents[1]

meta_path = PROJECT_ROOT / "data" / "embeddings" / "cpt_meta.parquet"
print(meta_path, meta_path.exists())

df = pd.read_parquet(meta_path)
df.head()

/Users/alifa/Documents/medical_cost_estimator_v2/data/embeddings/cpt_meta.parquet True

,faiss_id,search_text,description,code,title,type,category,clean_title,clean_description,search_terms
0,0,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",100,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology,None,None,None
1,1,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",102,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology,None,None,None
2,2,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",103,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology,None,None,None
3,3,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",104,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology,None,None,None
4,4,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",120,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology,None,None,None

In [16]:
df = pd.read_parquet(PROJECT_ROOT / "data" / "embeddings" / "cpt_meta.parquet")
df.columns.tolist()

['faiss_id',
 'search_text',
 'description',
 'code',
 'title',
 'type',
 'category',
 'clean_title',
 'clean_description',
 'search_terms']

In [17]:
df.head()

,faiss_id,search_text,description,code,title,type,category,clean_title,clean_description,search_terms
0,0,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",100,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology,None,None,None
1,1,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",102,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology,None,None,None
2,2,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",103,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology,None,None,None
3,3,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",104,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology,None,None,None
4,4,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",120,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology,None,None,None

In [18]:
df_enriched = pd.read_parquet(PROJECT_ROOT / "data" / "processed" / "cpt_hcpcs_enriched.parquet")
df_enriched.columns.tolist()
df_enriched.head()

,index,code,title,category,description,type,keywords,search_text,clean_title,clean_description,search_terms
0,0,100,"""Anesthesia for Procedures on the Head.Anesthe...",Anesthesiology,"""The provider performs anesthesia services for...",CPT,procedure salivary anesthesia services salivar...,"""Anesthesia for Procedures on the Head.Anesthe...",None,None,None
1,1,102,"""Anesthesia for Procedures on the Head.Anesthe...",Anesthesiology,"""The provider performs anesthesia services for...",CPT,cleft lip cleft repair cleft anesthesia servic...,"""Anesthesia for Procedures on the Head.Anesthe...",None,None,None
2,2,103,"""Anesthesia for Procedures on the Head.Anesthe...",Anesthesiology,"""The provider performs anesthesia services for...",CPT,anesthesia services eyelid blepharoplasty perf...,"""Anesthesia for Procedures on the Head.Anesthe...",None,None,None
3,3,104,"""Anesthesia for Procedures on the Head.Anesthe...",Anesthesiology,"""The provider performs anesthesia services for...",CPT,electroconvulsive therapy undergoing electroco...,"""Anesthesia for Procedures on the Head.Anesthe...",None,None,None
4,4,120,"""Anesthesia for Procedures on the Head.Anesthe...",Anesthesiology,"""The provider performs anesthesia services for...",CPT,anesthesia services performs anesthesia anesth...,"""Anesthesia for Procedures on the Head.Anesthe...",None,None,None

In [19]:
df_enriched[df_enriched["code"] == "77067"]

,index,code,title,category,description,type,keywords,search_text,clean_title,clean_description,search_terms
6573,6575,77067,"""Breast Mammography.Diagnostic Radiology. Mamm...",Radiology,"""The provider takes two X–ray views of each br...",CPT,views breast analyzes images abnormalities ima...,"[Patient-friendly title for 77067] ""The provid...",[Patient-friendly title for 77067],"""The provider takes two X–ray views of each br...","procedure 77067, code 77067"