In [4]:
from pathlib import Path
import pandas as pd


PROJECT_ROOT = Path.cwd().parents[1]

meta_path = PROJECT_ROOT / "data" / "embeddings" / "cpt_meta.parquet"
print(meta_path, meta_path.exists())

df = pd.read_parquet(meta_path)
df.head()

/Users/alifa/Documents/ml_projects/medical_cost_estimator/data/embeddings/cpt_meta.parquet True

,faiss_id,search_text,description,code,title,type,category
0,0,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",100,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology
1,1,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",102,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology
2,2,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",103,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology
3,3,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",104,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology
4,4,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",120,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology

In [5]:
df = pd.read_parquet(PROJECT_ROOT / "data" / "embeddings" / "cpt_meta.parquet")
df.columns.tolist()

['faiss_id', 'search_text', 'description', 'code', 'title', 'type', 'category']

In [6]:
df.head()

,faiss_id,search_text,description,code,title,type,category
0,0,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",100,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology
1,1,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",102,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology
2,2,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",103,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology
3,3,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",104,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology
4,4,"""Anesthesia for Procedures on the Head.Anesthe...","""The provider performs anesthesia services for...",120,"""Anesthesia for Procedures on the Head.Anesthe...",CPT,Anesthesiology